<script setup>
import { computed, defineAsyncComponent, onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import { Bar, Doughnut, Line } from 'vue-chartjs';
import { BarElement, CategoryScale, Chart as ChartJS, Filler, Legend, LinearScale, LineElement, PointElement, ArcElement, Tooltip } from 'chart.js';
import { ArrowUpRight, BellRing, CalendarDays, Car, ChevronRight, CircleAlert, Droplets, FileClock, Gauge, Package, Plus, ReceiptIndianRupee, RefreshCw, ShieldCheck, Sparkles, Wrench } from 'lucide-vue-next';
import api, { apiError } from '../services/api';
import { formatDate, formatDateTime, timezoneFor } from '../utils/datetime';
import MetricCard from '../components/MetricCard.vue';
const HomeScene = defineAsyncComponent(() => import('../components/HomeScene.vue'));
import { useAuthStore } from '../stores/auth';
ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, BarElement, ArcElement, Filler, Tooltip, Legend);
const auth = useAuthStore(); const router = useRouter(); const timezone = computed(() => timezoneFor(auth.user)); const dashboard = ref(null); const loading = ref(true); const error = ref('');
const money = (value) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: dashboard.value?.currency || 'INR', maximumFractionDigits: 0 }).format(Number(value || 0));
const load = async (refresh = false) => { loading.value = true; error.value = ''; try { dashboard.value = (await api.get('/dashboard', { params: refresh ? { refresh: 1 } : {} })).data; } catch (e) { error.value = apiError(e); } finally { loading.value = false; } };
onMounted(load);
const monthlyData = computed(() => ({ labels: dashboard.value?.charts?.monthly_expenses?.map((x) => x.label) || [], datasets: [{ label: 'Expenses', data: dashboard.value?.charts?.monthly_expenses?.map((x) => x.value) || [], borderColor: '#75e6bd', backgroundColor: 'rgba(117,230,189,.14)', fill: true, tension: .42, pointRadius: 3, pointBackgroundColor: '#b4ffe0' }] }));
const categoryData = computed(() => ({ labels: dashboard.value?.charts?.category_breakdown?.map((x) => x.label) || [], datasets: [{ data: dashboard.value?.charts?.category_breakdown?.map((x) => x.value) || [], backgroundColor: ['#75e6bd', '#5eb9e8', '#a98be8', '#f5bd69', '#ef8395', '#5fd1c1', '#d1e267'], borderWidth: 0 }] }));
const maintenanceData = computed(() => ({ labels: dashboard.value?.charts?.maintenance_expenses?.map((x) => x.label) || [], datasets: [{ label: 'Maintenance', data: dashboard.value?.charts?.maintenance_expenses?.map((x) => x.value) || [], backgroundColor: 'rgba(117,230,189,.72)', borderRadius: 6, barThickness: 14 }] }));
const chartOptions = { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } }, scales: { x: { grid: { display: false }, ticks: { color: '#70998e', font: { size: 10 } } }, y: { grid: { color: 'rgba(155,246,210,.08)' }, ticks: { color: '#70998e', font: { size: 10 }, callback: (v) => `₹${v / 1000}k` } } } };
const doughnutOptions = { responsive: true, maintainAspectRatio: false, cutout: '72%', plugins: { legend: { display: false } } };
const roomModule = { 'Living room': 'expenses', Kitchen: 'bills', Bedroom: 'assets', Garden: 'garden' };
const goRoom = (room) => router.push(`/modules/${roomModule[room] || 'tasks'}`);
const alertCards = computed(() => dashboard.value ? [{ key: 'bills', label: 'Bills & payments', icon: ReceiptIndianRupee, tone: 'amber', items: dashboard.value.alerts.bills ?? dashboard.value.alerts.upcomingBills ?? [], to: 'bills' }, { key: 'maintenance', label: 'Maintenance', icon: Wrench, tone: 'red', items: dashboard.value.alerts.maintenance ?? [], to: 'maintenance' }, { key: 'tasks', label: 'Tasks', icon: Gauge, tone: 'blue', items: dashboard.value.alerts.tasks ?? [], to: 'tasks' }, { key: 'inventory', label: 'Inventory', icon: Package, tone: 'green', items: dashboard.value.alerts.inventory ?? dashboard.value.alerts.lowStock ?? [], to: 'inventory' }] : []);
</script>
<template>
    <div class="mx-auto max-w-[1600px] space-y-6 fade-up"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="eyebrow flex items-center gap-2"><Sparkles :size="13" /> {{ formatDate(new Date(), timezone) }}</p><h1 class="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Good morning, {{ auth.user?.name?.split(' ')[0] }}.</h1><p class="mt-2 text-sm text-[#86ada3]">Here’s the pulse of your household today.</p></div><div class="flex gap-2"><button class="btn-secondary" :disabled="loading" @click="load(true)"><RefreshCw :size="15" :class="loading ? 'animate-spin' : ''" /> Refresh</button><button class="btn-primary" @click="router.push('/modules/expenses')"><Plus :size="16" /> Add expense</button></div></div>
        <div v-if="error" class="rounded-xl border border-rose-300/20 bg-rose-400/10 px-4 py-3 text-sm text-rose-200">{{ error }}</div><div v-if="loading && !dashboard" class="grid grid-cols-2 gap-3 lg:grid-cols-4"><div v-for="i in 8" :key="i" class="h-28 rounded-2xl skeleton"></div></div><template v-if="dashboard"><div class="grid grid-cols-2 gap-3 lg:grid-cols-4"><MetricCard label="This month" :value="money(dashboard.metrics.monthly_expenses)" :detail="`${money(dashboard.metrics.budget_remaining)} budget left`" :icon="ReceiptIndianRupee"/><MetricCard label="Year to date" :value="money(dashboard.metrics.yearly_expenses)" detail="Across all properties" tone="blue" :icon="ArrowUpRight"/><MetricCard label="Due soon" :value="dashboard.metrics.upcoming_bills_count" :detail="`${money(dashboard.metrics.upcoming_bills_amount)} scheduled`" tone="amber" :icon="BellRing"/><MetricCard label="Home attention" :value="dashboard.metrics.open_maintenance + dashboard.metrics.pending_tasks" :detail="`${dashboard.metrics.open_maintenance} maintenance · ${dashboard.metrics.pending_tasks} tasks`" tone="red" :icon="Wrench"/></div><HomeScene @select="goRoom"/><div class="grid gap-5 xl:grid-cols-[1.4fr_.8fr_.8fr]"><section class="panel p-4 sm:p-5"><div class="mb-4 flex items-center justify-between"><div><p class="eyebrow">Cashflow</p><h2 class="mt-1 font-semibold">Monthly expenses</h2></div><span class="badge badge-green">12 months</span></div><div class="h-52"><Line :data="monthlyData" :options="chartOptions" /></div></section><section class="panel p-4 sm:p-5"><div class="mb-4"><p class="eyebrow">Composition</p><h2 class="mt-1 font-semibold">By category</h2></div><div class="flex h-52 items-center gap-4"><div class="h-40 w-40 shrink-0"><Doughnut :data="categoryData" :options="doughnutOptions" /></div><div class="min-w-0 space-y-2 text-xs text-[#9ac2b5]"><div v-for="(item, index) in dashboard.charts.category_breakdown.slice(0, 5)" :key="item.label" class="flex items-center gap-2"><span class="h-2 w-2 rounded-full" :style="{ background: ['#75e6bd','#5eb9e8','#a98be8','#f5bd69','#ef8395'][index] }"></span><span class="truncate">{{ item.label }}</span><span class="ml-auto text-white">{{ money(item.value) }}</span></div></div></div></section><section class="panel p-4 sm:p-5"><div class="mb-4"><p class="eyebrow">Service ledger</p><h2 class="mt-1 font-semibold">Maintenance costs</h2></div><div class="h-52"><Bar :data="maintenanceData" :options="chartOptions" /></div></section></div>
        <div class="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><section class="panel p-4 sm:p-5"><div class="mb-4 flex items-center justify-between"><div><p class="eyebrow">Action center</p><h2 class="mt-1 font-semibold">What needs your attention</h2></div><CircleAlert :size="18" class="text-amber-200" /></div><div class="grid gap-3 sm:grid-cols-2"><button v-for="card in alertCards" :key="card.key" class="group rounded-2xl border border-emerald-100/10 bg-[#082b27] p-4 text-left transition hover:border-emerald-200/30 hover:bg-[#0c3831]" @click="router.push(`/modules/${card.to}`)"><div class="flex items-start justify-between"><span class="flex h-9 w-9 items-center justify-center rounded-xl" :class="card.tone === 'red' ? 'bg-rose-400/10 text-rose-200' : card.tone === 'amber' ? 'bg-amber-400/10 text-amber-200' : card.tone === 'blue' ? 'bg-sky-400/10 text-sky-200' : 'bg-emerald-400/10 text-emerald-200'"><component :is="card.icon" :size="17" /></span><ChevronRight :size="15" class="text-[#507e72] transition group-hover:translate-x-1 group-hover:text-emerald-200" /></div><p class="mt-4 text-sm font-semibold">{{ card.label }}</p><p class="mt-1 text-xs text-[#7da99c]">{{ card.items.length }} items need review</p><div class="mt-3 flex -space-x-1.5"><span v-for="item in card.items.slice(0, 3)" :key="item.id" class="flex h-6 w-6 items-center justify-center rounded-full border-2 border-[#082b27] bg-[#1a5b4e] text-[9px] text-emerald-100">{{ (item.name || item.title || 'Item').slice(0, 1) }}</span><span v-if="card.items.length > 3" class="flex h-6 w-6 items-center justify-center rounded-full border-2 border-[#082b27] bg-[#123f38] text-[9px] text-emerald-200">+{{ card.items.length - 3 }}</span></div></button></div></section><section class="panel p-4 sm:p-5"><div class="mb-4"><p class="eyebrow">Household timeline</p><h2 class="mt-1 font-semibold">Recent activity</h2></div><div class="space-y-3"><div v-for="activity in dashboard.recent_activity" :key="activity.id" class="flex gap-3"><span class="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-emerald-300 shadow-[0_0_9px_#75e6bd]"></span><div class="min-w-0 flex-1"><p class="truncate text-xs text-[#c3e8d9]"><strong class="text-white">{{ activity.user?.name || 'System' }}</strong> {{ activity.action }} {{ activity.module }}</p><p class="mt-1 text-[10px] text-[#5f8b80]">{{ formatDateTime(activity.created_at, timezone) }}</p></div></div><p v-if="!dashboard.recent_activity?.length" class="text-xs text-[#719b8e]">Activity will appear here as your household changes.</p></div></section></div></template>
    </div>
</template>
