<script setup>
import { onMounted, ref } from 'vue';
import { Bell, CheckCheck, LoaderCircle, RefreshCw } from 'lucide-vue-next';
import api, { apiError } from '../services/api';
import { formatDateTime, timezoneFor } from '../utils/datetime';
import { useAuthStore } from '../stores/auth';
const auth = useAuthStore(); const timezone = timezoneFor(auth.user);
const notifications = ref([]); const meta = ref({ unread: 0 }); const loading = ref(true); const error = ref('');
const load = async () => { loading.value = true; try { const data = (await api.get('/notifications')).data; notifications.value = data.data; meta.value = data.meta; } catch (e) { error.value = apiError(e); } finally { loading.value = false; } };
const read = async (item) => { if (!item.read_at) { await api.post(`/notifications/${item.id}/read`); item.read_at = new Date().toISOString(); meta.value.unread--; } }; const readAll = async () => { await api.post('/notifications/read-all'); notifications.value.forEach((item) => item.read_at = item.read_at || new Date().toISOString()); meta.value.unread = 0; }; onMounted(load);
</script>
<template><div class="mx-auto max-w-4xl space-y-5 fade-up"><div class="flex items-end justify-between gap-3"><div><p class="eyebrow flex items-center gap-2"><Bell :size="13" /> Stay in sync</p><h1 class="mt-2 text-3xl font-semibold">Notifications</h1><p class="mt-1 text-sm text-[#86ada3]">Reminders and important changes from across your home.</p></div><div class="flex gap-2"><button class="icon-btn" title="Refresh" @click="load"><RefreshCw :size="15" :class="loading ? 'animate-spin' : ''" /></button><button class="btn-secondary" :disabled="!meta.unread" @click="readAll"><CheckCheck :size="15" /> Mark all read</button></div></div><p v-if="error" class="rounded-xl bg-rose-400/10 px-4 py-3 text-sm text-rose-200">{{ error }}</p><div v-if="loading" class="panel space-y-2 p-4"><div v-for="i in 5" :key="i" class="h-16 rounded-xl skeleton"></div></div><div v-else-if="!notifications.length" class="panel flex flex-col items-center py-20 text-center"><Bell :size="30" class="text-emerald-200/60"/><p class="mt-3 text-sm text-[#86ada3]">You’re all caught up.</p></div><div v-else class="space-y-2"><button v-for="item in notifications" :key="item.id" class="panel panel-hover flex w-full items-start gap-3 p-4 text-left" :class="!item.read_at ? 'border-emerald-200/25' : 'opacity-70'" @click="read(item)"><span class="mt-1 flex h-9 w-9 shrink-0 items-center justify-center rounded-xl" :class="item.read_at ? 'bg-white/5 text-[#719b8e]' : 'bg-emerald-300/10 text-emerald-200'"><Bell :size="16" /></span><span class="min-w-0 flex-1"><span class="block text-sm font-semibold text-white">{{ item.title }}</span><span class="mt-1 block text-xs leading-5 text-[#8eb8aa]">{{ item.message }}</span><span class="mt-2 block text-[10px] text-[#5f8b80]">{{ formatDateTime(item.created_at, timezone) }}</span></span><span v-if="!item.read_at" class="mt-2 h-2 w-2 rounded-full bg-emerald-300 shadow-[0_0_8px_#75e6bd]"></span></button></div></div></template>
