<script setup>
import { onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import { ArrowUpRight, FileSearch, Search, Sparkles } from 'lucide-vue-next';
import api, { apiError } from '../services/api';
const router = useRouter(); const query = ref(''); const results = ref({}); const loading = ref(false); const error = ref('');
const run = async () => { if (query.value.trim().length < 2) { results.value = {}; return; } loading.value = true; error.value = ''; try { results.value = (await api.get('/search', { params: { q: query.value } })).data.results; } catch (e) { error.value = apiError(e); } finally { loading.value = false; } };
const open = (module, id) => router.push(`/modules/${module}/${id}`); onMounted(run);
</script>
<template><div class="mx-auto max-w-5xl space-y-6 fade-up"><div><p class="eyebrow flex items-center gap-2"><Sparkles :size="13" /> Universal search</p><h1 class="mt-2 text-3xl font-semibold">Find anything in your home.</h1><p class="mt-2 text-sm text-[#86ada3]">Search expenses, bills, assets, people, vehicles, documents, and more.</p></div><div class="panel p-4"><div class="relative"><Search :size="19" class="absolute left-4 top-1/2 -translate-y-1/2 text-emerald-200"/><input v-model="query" autofocus class="field h-14 pl-12 text-base" placeholder="Try “AC”, “groceries”, or “renewal”…" @input="run"/></div></div><p v-if="error" class="rounded-xl bg-rose-400/10 px-4 py-3 text-sm text-rose-200">{{ error }}</p><div v-if="loading" class="panel p-10 text-center text-sm text-[#7da99c]">Searching your permission-scoped home data…</div><div v-else-if="query.length < 2" class="panel flex flex-col items-center py-16 text-center"><FileSearch :size="32" class="text-emerald-200/60"/><p class="mt-4 text-sm text-[#7da99c]">Enter at least two characters to begin.</p></div><div v-else-if="!Object.keys(results).length" class="panel flex flex-col items-center py-16 text-center"><FileSearch :size="32" class="text-emerald-200/60"/><p class="mt-4 text-sm text-[#7da99c]">No matching records found.</p></div><div v-else class="space-y-4"><section v-for="(group, key) in results" :key="key" class="panel overflow-hidden"><div class="border-b border-emerald-100/10 px-5 py-3 text-xs font-bold uppercase tracking-[.14em] text-emerald-200/70">{{ group.label }}</div><button v-for="item in group.items" :key="item.id" class="flex w-full items-center gap-3 border-t border-emerald-100/5 px-5 py-4 text-left transition hover:bg-emerald-200/5" @click="open(key, item.id)"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-emerald-300/10 text-emerald-200"><Search :size="15" /></span><span class="min-w-0 flex-1"><span class="block truncate text-sm text-white">{{ item.title }}</span><span class="block text-xs text-[#6e9b8e]">{{ item.subtitle || 'Household record' }}</span></span><ArrowUpRight :size="16" class="text-[#609184]"/></button></section></div></div></template>
