<script setup>
import { onMounted, reactive, ref } from 'vue';
import { Check, Globe2, Plus, Save, Settings as SettingsIcon, ShieldCheck, UsersRound } from 'lucide-vue-next';
import api, { apiError } from '../services/api';
import { useAuthStore } from '../stores/auth';
import HouseholdPanel from '../components/HouseholdPanel.vue';
import AccessControlPanel from '../components/AccessControlPanel.vue';
const auth = useAuthStore(); const loading = ref(true); const saving = ref(false); const error = ref(''); const notice = ref(''); const settings = ref(null); const users = ref([]); const selectedHouseholdId = ref(null); const selectedHouseholdName = ref(''); const showCategory = ref(false); const category = reactive({ type: 'expense', name: '', color: '#6ee7b7' });
const load = async () => { loading.value = true; try { settings.value = (await api.get('/settings')).data; if (auth.isAdmin) users.value = (await api.get('/settings/users')).data.data; } catch (e) { error.value = apiError(e); } finally { loading.value = false; } };
const save = async () => { saving.value = true; notice.value = ''; try { await api.put('/settings', settings.value.household); notice.value = 'Settings saved.'; } catch (e) { error.value = apiError(e); } finally { saving.value = false; } };
const saveCategory = async () => { try { await api.post('/settings/categories', category); category.name = ''; showCategory.value = false; await load(); } catch (e) { error.value = apiError(e); } };
const selectHousehold = async (household) => { selectedHouseholdId.value = household.id; selectedHouseholdName.value = household.name; try { users.value = (await api.get(`/households/${household.id}/users`)).data.data; } catch (e) { error.value = apiError(e); } };
const changeRole = async (person, event) => { try { await api.put(`/settings/users/${person.id}/role`, { role: event.target.value }); notice.value = `Role updated for ${person.name}.`; } catch (e) { error.value = apiError(e); } };
onMounted(load);
</script>
<template><div class="mx-auto max-w-6xl space-y-5 fade-up"><div><p class="eyebrow flex items-center gap-2"><SettingsIcon :size="13" /> Control center</p><h1 class="mt-2 text-3xl font-semibold">Settings</h1><p class="mt-1 text-sm text-[#86ada3]">Configure your household workspace, categories, and access model.</p></div><p v-if="error" class="rounded-xl bg-rose-400/10 px-4 py-3 text-sm text-rose-200">{{ error }}</p><p v-if="notice" class="rounded-xl bg-emerald-300/10 px-4 py-3 text-sm text-emerald-100">{{ notice }}</p><div v-if="loading" class="panel h-64 skeleton"></div><template v-else-if="settings"><section class="panel p-5 sm:p-6"><div class="flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-300/10 text-emerald-200"><Globe2 :size="18" /></span><div><h2 class="font-semibold">Household preferences</h2><p class="text-xs text-[#719b8e]">Used across dashboards, reports, reminders, and AI answers.</p></div></div><div class="mt-6 grid gap-4 sm:grid-cols-2"><div><label class="label">Household name</label><input v-model="settings.household.name" class="field" /></div><div><label class="label">Timezone</label><select v-model="settings.household.timezone" class="field"><option>Asia/Kolkata</option><option>UTC</option><option>Asia/Dubai</option><option>Europe/London</option><option>America/New_York</option></select></div><div><label class="label">Currency</label><select v-model="settings.household.currency" class="field"><option>INR</option><option>USD</option><option>EUR</option><option>GBP</option><option>AED</option></select></div><div><label class="label">Address</label><input v-model="settings.household.address" class="field" /></div></div><button class="btn-primary mt-5" :disabled="saving" @click="save"><Save :size="15" /> {{ saving ? 'Saving…' : 'Save preferences' }}</button></section>
    <div class="grid gap-5 lg:grid-cols-2"><section class="panel p-5 sm:p-6"><div class="flex items-center justify-between"><div class="flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-cyan-300/10 text-cyan-200"><ShieldCheck :size="18" /></span><div><h2 class="font-semibold">Categories</h2><p class="text-xs text-[#719b8e]">Shared labels for consistent reporting.</p></div></div><button class="icon-btn" @click="showCategory = !showCategory"><Plus :size="16" /></button></div><form v-if="showCategory" class="mt-4 grid grid-cols-2 gap-2 rounded-xl border border-emerald-100/10 bg-[#082b27] p-3" @submit.prevent="saveCategory"><input v-model="category.name" class="field col-span-2" placeholder="Category name" required/><select v-model="category.type" class="field"><option value="expense">Expense</option><option value="bill">Bill</option><option value="maintenance">Maintenance</option><option value="asset">Asset</option><option value="document">Document</option></select><button class="btn-primary"><Check :size="15" /> Add</button></form><div class="mt-5 max-h-64 space-y-2 overflow-y-auto"><div v-for="item in settings.categories" :key="item.id" class="flex items-center gap-2 rounded-lg bg-[#082b27] px-3 py-2"><span class="h-2 w-2 rounded-full" :style="{ background: item.color }"></span><span class="flex-1 text-xs text-[#c1e4d6]">{{ item.name }}</span><span class="text-[10px] uppercase text-[#5f8b80]">{{ item.type }}</span></div></div></section><section class="panel p-5 sm:p-6"><div class="flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-300/10 text-violet-200"><UsersRound :size="18" /></span><div><h2 class="font-semibold">People & roles<span v-if="selectedHouseholdName"> · {{ selectedHouseholdName }}</span></h2><p class="text-xs text-[#719b8e]">Role changes apply to the selected family only.</p></div></div><div v-if="!auth.isAdmin" class="mt-6 rounded-xl bg-[#082b27] p-4 text-sm text-[#8eb8aa]">Only administrators can manage household roles.</div><div v-else class="mt-5 space-y-2"><div v-for="person in users" :key="person.id" class="flex items-center gap-3 rounded-xl bg-[#082b27] p-3"><span class="flex h-8 w-8 items-center justify-center rounded-lg bg-emerald-200/15 text-xs font-bold text-emerald-100">{{ person.name.slice(0, 1) }}</span><div class="min-w-0 flex-1"><p class="truncate text-xs font-semibold text-white">{{ person.name }}</p><p class="truncate text-[10px] text-[#6e9b8e]">{{ person.email }}</p></div><select class="field w-auto min-w-[110px] py-1.5 text-xs" :value="person.roles?.[0]?.name" @change="changeRole(person, $event)"><option v-for="role in settings.roles" :key="role.id" :value="role.name">{{ role.name.replace('-', ' ') }}</option></select></div></div></section></div>
</template><AccessControlPanel v-if="auth.isAdmin" :household-id="selectedHouseholdId" /><HouseholdPanel v-if="auth.isAdmin" @selected="selectHousehold" /></div></template>
