<script setup>
import { nextTick, ref, watch } from 'vue';
import { Bot, ChevronDown, Mic, Send, Sparkles, Trash2, X } from 'lucide-vue-next';
import api, { apiError } from '../services/api';
const props = defineProps({ open: Boolean }); const emit = defineEmits(['close', 'listening', 'processing']);
const text = ref(''); const messages = ref([]); const listening = ref(false); const processing = ref(false); const error = ref(''); const body = ref(null); let recognition;
const scroll = () => nextTick(() => body.value?.scrollTo({ top: body.value.scrollHeight, behavior: 'smooth' }));
watch(() => props.open, async (value) => { if (value) { try { messages.value = (await api.get('/ai/history')).data.data || []; } catch {} scroll(); } });
const send = async () => { const message = text.value.trim(); if (!message || processing.value) return; text.value = ''; error.value = ''; messages.value.push({ role: 'user', content: message }); processing.value = true; emit('processing', true); scroll(); try { const result = (await api.post('/ai/chat', { message })).data; messages.value.push({ role: 'assistant', content: result.message }); } catch (e) { error.value = apiError(e); } finally { processing.value = false; emit('processing', false); scroll(); } };
const voice = () => { if (listening.value) { recognition?.stop(); return; } const Speech = window.SpeechRecognition || window.webkitSpeechRecognition; if (!Speech) { error.value = 'Voice input is not supported in this browser.'; return; } recognition = new Speech(); recognition.lang = 'en-IN'; recognition.interimResults = true; recognition.onstart = () => { listening.value = true; emit('listening', true); }; recognition.onresult = (event) => { text.value = Array.from(event.results).map((result) => result[0].transcript).join(''); }; recognition.onerror = () => { error.value = 'I could not hear that. Please try again.'; }; recognition.onend = () => { listening.value = false; emit('listening', false); }; recognition.start(); };
const clear = async () => { await api.delete('/ai/history'); messages.value = []; };
</script>
<template>
    <div v-if="open" class="glass fixed bottom-[6.1rem] right-3 z-50 flex w-[calc(100vw-1.5rem)] max-w-[390px] flex-col overflow-hidden rounded-[1.35rem] shadow-2xl sm:right-5">
        <div class="flex items-center justify-between border-b border-emerald-100/10 px-4 py-3"><div class="flex items-center gap-2.5"><div class="flex h-8 w-8 items-center justify-center rounded-xl bg-emerald-300/15 text-emerald-200"><Bot :size="17" /></div><div><p class="text-sm font-semibold text-white">NOVA · Home assistant</p><p class="text-[10px] text-emerald-200/60">Permission-aware intelligence</p></div></div><div class="flex gap-1"><button class="icon-btn h-7 w-7 border-0 bg-transparent" title="Clear conversation" @click="clear"><Trash2 :size="14" /></button><button class="icon-btn h-7 w-7 border-0 bg-transparent" title="Close" @click="emit('close')"><X :size="16" /></button></div></div>
        <div ref="body" class="max-h-[52vh] min-h-[220px] space-y-3 overflow-y-auto px-4 py-4"><div class="flex gap-2.5"><div class="mt-1 flex h-6 w-6 shrink-0 items-center justify-center rounded-lg bg-emerald-300/15 text-emerald-200"><Sparkles :size="12" /></div><div class="max-w-[85%] rounded-2xl rounded-tl-sm bg-[#123b35] px-3 py-2.5 text-xs leading-5 text-[#d8f8e9]">Hi! Ask me about your spending, bills, home services, or what needs attention this week.</div></div><div v-for="(message, index) in messages" :key="index" class="flex gap-2.5" :class="message.role === 'user' ? 'justify-end' : ''"><div v-if="message.role !== 'user'" class="mt-1 flex h-6 w-6 shrink-0 items-center justify-center rounded-lg bg-emerald-300/15 text-emerald-200"><Bot :size="12" /></div><div class="max-w-[85%] whitespace-pre-line rounded-2xl px-3 py-2.5 text-xs leading-5" :class="message.role === 'user' ? 'rounded-tr-sm bg-emerald-300/15 text-emerald-50' : 'rounded-tl-sm bg-[#123b35] text-[#d8f8e9]'">{{ message.content }}</div></div><div v-if="processing" class="flex items-center gap-2 text-xs text-emerald-200/60"><span class="h-1.5 w-1.5 animate-bounce rounded-full bg-emerald-300"/><span class="h-1.5 w-1.5 animate-bounce rounded-full bg-emerald-300 [animation-delay:120ms]"/><span class="h-1.5 w-1.5 animate-bounce rounded-full bg-emerald-300 [animation-delay:240ms]"/> Thinking through your home data…</div><p v-if="error" class="rounded-xl bg-rose-400/10 px-3 py-2 text-xs text-rose-200">{{ error }}</p></div>
        <div class="border-t border-emerald-100/10 p-3"><div class="flex items-end gap-2 rounded-2xl border border-emerald-100/15 bg-[#062421] p-2"><button class="icon-btn h-8 w-8 shrink-0 border-0 bg-transparent" :class="listening ? 'text-amber-300' : 'text-emerald-200/70'" title="Speak" @click="voice"><Mic :size="16" /></button><textarea v-model="text" rows="1" class="max-h-24 min-h-8 flex-1 resize-none border-0 bg-transparent px-1 py-1.5 text-xs text-white outline-none placeholder:text-[#5e887c]" placeholder="Ask about your home…" @keydown.enter.exact.prevent="send"></textarea><button class="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-emerald-300 text-[#062421] disabled:opacity-40" :disabled="!text.trim() || processing" title="Send" @click="send"><Send :size="14" /></button></div><p class="mt-2 px-1 text-[10px] text-[#5d887c]">Voice converts to editable text before sending. Your access rules always apply.</p></div>
    </div>
</template>
