<script setup>
import { onBeforeUnmount, onMounted, ref, watch } from 'vue';
import * as THREE from 'three';
import { Bot, Mic, Send, Sparkles, X } from 'lucide-vue-next';
const props = defineProps({ open: Boolean, listening: Boolean, processing: Boolean });
const emit = defineEmits(['toggle']);
const canvas = ref(null); const sceneError = ref(false); let renderer, scene, camera, bot, ring, frame, observer;
const color = () => props.processing ? 0x77b9ff : props.listening ? 0xffc978 : 0x71efc3;
function build(){scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(32,1,.1,10);camera.position.z=3.2;renderer=new THREE.WebGLRenderer({canvas:canvas.value,alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));scene.add(new THREE.HemisphereLight(0xc8fff0,0x092522,2));const light=new THREE.PointLight(color(),5,8);light.position.set(1,2,3);scene.add(light);bot=new THREE.Group();const body=new THREE.Mesh(new THREE.SphereGeometry(.72,24,16),new THREE.MeshStandardMaterial({color:0x143e3a,roughness:.25,metalness:.55}));body.scale.set(1,.78,1);bot.add(body);const face=new THREE.Mesh(new THREE.SphereGeometry(.51,20,12,0,Math.PI*2,0,Math.PI/2),new THREE.MeshStandardMaterial({color:0x9af6d0,emissive:0x237c67,emissiveIntensity:.7,roughness:.3}));face.rotation.x=Math.PI;face.position.set(0,.1,.52);bot.add(face);[-.18,.18].forEach(x=>{const eye=new THREE.Mesh(new THREE.SphereGeometry(.06,12,8),new THREE.MeshBasicMaterial({color:0x06221e}));eye.position.set(x,.18,.98);bot.add(eye);});ring=new THREE.Mesh(new THREE.TorusGeometry(.92,.025,8,48),new THREE.MeshBasicMaterial({color:0x9af6d0,transparent:true,opacity:.8}));ring.rotation.x=Math.PI/2.5;bot.add(ring);scene.add(bot);resize();animate();}
function resize(){if(!renderer)return;const b=canvas.value.getBoundingClientRect();renderer.setSize(b.width,b.height,false);camera.aspect=b.width/b.height;camera.updateProjectionMatrix();}
function animate(){frame=requestAnimationFrame(animate);bot.rotation.y+=props.listening?.035:.012;bot.position.y=Math.sin(performance.now()*.002)*.06;ring.rotation.z+=.01;renderer.render(scene,camera);}
watch(() => [props.listening,props.processing],()=>{if(scene)scene.traverse(o=>{if(o.material?.emissive)o.material.emissive.setHex(color());if(o.material?.color&&o.material.color.getHex()===0x71efc3)o.material.color.setHex(color());});});
onMounted(()=>{try{build();observer=new ResizeObserver(resize);observer.observe(canvas.value);}catch(error){console.warn('AI mascot 3D unavailable',error);sceneError.value=true;}});onBeforeUnmount(()=>{cancelAnimationFrame(frame);observer?.disconnect();renderer?.dispose();scene?.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});});
</script>
<template><button class="ai-launcher pulse-soft" :class="{ 'is-open': open, 'is-listening': listening }" :aria-label="open ? 'Close AI assistant' : 'Open AI assistant'" @click="emit('toggle')"><canvas v-show="!sceneError" ref="canvas" class="ai-canvas"></canvas><span v-if="sceneError" class="absolute inset-2 flex items-center justify-center rounded-2xl bg-emerald-300/20 text-2xl">✦</span><span class="ai-glow"></span><span class="ai-badge"><Bot :size="12" /> AI</span><span v-if="listening" class="absolute -right-1 -top-1 h-3 w-3 animate-ping rounded-full bg-amber-300"/><span v-else-if="processing" class="absolute -right-1 -top-1 h-3 w-3 animate-ping rounded-full bg-sky-300"/></button></template>
