<script setup>
import { computed, defineAsyncComponent, onMounted, ref, watch } from 'vue';
import { RouterLink, RouterView, useRoute, useRouter } from 'vue-router';
import { BarChart3, Bell, BriefcaseBusiness, CalendarDays, Car, CheckSquare, ChevronRight, FileText, FolderLock, Home, LayoutDashboard, LogOut, Menu, Package, PawPrint, ReceiptIndianRupee, Repeat2, Search, Settings, ShieldCheck, Sprout, Target, UserRound, UsersRound, Wrench, X } from 'lucide-vue-next';
import { useAuthStore } from '../stores/auth';
import api, { apiError } from '../services/api';
const AiMascot = defineAsyncComponent(() => import('./AiMascot.vue'));
const AiChat = defineAsyncComponent(() => import('./AiChat.vue'));
const auth = useAuthStore(); const route = useRoute(); const router = useRouter();
const sidebarOpen = ref(false); const aiOpen = ref(false); const query = ref(''); const searchResults = ref([]); const notifications = ref(0); let searchTimer;
const moduleGroups = [
    { label: 'Command center', items: [{ label: 'Dashboard', to: '/', icon: LayoutDashboard }, { label: 'Global search', to: '/search', icon: Search }] },
    { label: 'Household', items: [{ label: 'Expenses', key: 'expenses', icon: ReceiptIndianRupee }, { label: 'Bills & payments', key: 'bills', icon: FileText }, { label: 'Budgets', key: 'budgets', icon: Target }, { label: 'Family members', key: 'family', icon: UsersRound }, { label: 'Properties', key: 'properties', icon: Home }] },
    { label: 'Home operations', items: [{ label: 'Maintenance', key: 'maintenance', icon: Wrench }, { label: 'Assets', key: 'assets', icon: Package }, { label: 'Tasks', key: 'tasks', icon: CheckSquare }, { label: 'Inventory', key: 'inventory', icon: Package }, { label: 'Calendar', key: 'calendar', icon: CalendarDays }] },
    { label: 'Assets & protection', items: [{ label: 'Subscriptions', key: 'subscriptions', icon: Repeat2 }, { label: 'Insurance', key: 'insurance', icon: ShieldCheck }, { label: 'Vehicles', key: 'vehicles', icon: Car }, { label: 'Documents', key: 'documents', icon: FolderLock }, { label: 'Providers', key: 'providers', icon: BriefcaseBusiness }] },
    { label: 'Lifestyle', items: [{ label: 'Home security', key: 'security', icon: ShieldCheck }, { label: 'Garden', key: 'garden', icon: Sprout }, { label: 'Pets', key: 'pets', icon: PawPrint }] },
];
const initials = computed(() => (auth.user?.name || 'H').split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase());
const allowed = (item) => !item.key || auth.can(`${item.key}.view`) || ['admin', 'super-admin'].some((role) => auth.user?.roles?.includes(role));
const visibleGroups = computed(() => moduleGroups.map((group) => ({ ...group, items: group.items.filter(allowed) })).filter((group) => group.items.length));
const loadNotifications = async () => { try { notifications.value = (await api.get('/notifications', { params: { per_page: 1 } })).data.meta.unread; } catch {} };
const runSearch = () => { clearTimeout(searchTimer); if (query.value.trim().length < 3) { searchResults.value = []; return; } searchTimer = setTimeout(async () => { try { searchResults.value = Object.entries((await api.get('/search', { params: { q: query.value } })).data.results).flatMap(([key, group]) => group.items.map((item) => ({ ...item, module: key, group: group.label }))); } catch {} }, 280); };
const goSearch = (item) => { query.value = ''; searchResults.value = []; router.push(`/modules/${item.module}/${item.id}`); };
const logout = async () => { await auth.logout(); router.push('/login'); };
watch(() => route.fullPath, () => { sidebarOpen.value = false; searchResults.value = []; });
onMounted(loadNotifications);
</script>
<template>
    <div class="mesh-bg min-h-screen text-white"><div v-if="sidebarOpen" class="fixed inset-0 z-30 bg-black/60 md:hidden" @click="sidebarOpen = false"></div>
        <aside class="fixed inset-y-0 left-0 z-40 flex w-[268px] -translate-x-full flex-col border-r border-emerald-100/10 bg-[#061d1b]/95 px-4 py-5 backdrop-blur-xl transition-transform md:translate-x-0" :class="sidebarOpen ? 'translate-x-0' : ''">
            <div class="mb-8 flex items-center justify-between px-2"><RouterLink to="/" class="flex items-center gap-3"><span class="relative flex h-10 w-10 items-center justify-center rounded-2xl bg-gradient-to-br from-emerald-200 to-cyan-300 text-[#062421] shadow-lg shadow-emerald-900/30"><span class="absolute h-5 w-5 rotate-45 rounded-[5px] border-2 border-[#062421]/70"/><span class="h-2 w-2 rounded-full bg-[#062421]"/></span><span><span class="block text-sm font-bold tracking-wide">NOVA HOME</span><span class="block text-[10px] text-emerald-200/55">ERP · 3D control</span></span></RouterLink><button class="icon-btn border-0 bg-transparent md:hidden" @click="sidebarOpen = false"><X :size="17" /></button></div>
            <nav class="flex-1 space-y-6 overflow-y-auto pr-1"><div v-for="group in visibleGroups" :key="group.label"><p class="mb-2 px-3 text-[10px] font-bold uppercase tracking-[.18em] text-[#5f8b80]">{{ group.label }}</p><div class="space-y-1"><template v-for="item in group.items" :key="item.label"><RouterLink v-if="item.to" :to="item.to" class="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-[#91b7ac] transition hover:bg-emerald-200/10 hover:text-emerald-100" :class="route.path === item.to ? 'bg-emerald-200/10 text-emerald-100 shadow-inner' : ''"><component :is="item.icon" :size="17" /><span>{{ item.label }}</span><ChevronRight v-if="route.path === item.to" :size="14" class="ml-auto text-emerald-300" /></RouterLink><RouterLink v-else :to="`/modules/${item.key}`" class="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-[#91b7ac] transition hover:bg-emerald-200/10 hover:text-emerald-100" :class="route.path.includes(`/modules/${item.key}`) ? 'bg-emerald-200/10 text-emerald-100 shadow-inner' : ''"><component :is="item.icon" :size="17" /><span>{{ item.label }}</span><ChevronRight v-if="route.path.includes(`/modules/${item.key}`)" :size="14" class="ml-auto text-emerald-300" /></RouterLink></template></div></div></nav>
            <div class="mt-5 border-t border-emerald-100/10 pt-4"><RouterLink to="/reports" class="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-[#91b7ac] hover:bg-emerald-200/10 hover:text-emerald-100"><BarChart3 :size="17" /> Reports & exports</RouterLink><RouterLink v-if="auth.can('settings.view') || auth.isAdmin" to="/settings" class="mt-1 flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-[#91b7ac] hover:bg-emerald-200/10 hover:text-emerald-100"><Settings :size="17" /> Settings</RouterLink><RouterLink to="/profile" class="mt-1 flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-[#91b7ac] hover:bg-emerald-200/10 hover:text-emerald-100"><UserRound :size="17" /> Profile & sessions</RouterLink></div>
        </aside>
        <div class="md:pl-[268px]"><header class="sticky top-0 z-20 border-b border-emerald-100/10 bg-[#061b1a]/75 backdrop-blur-xl"><div class="flex h-[72px] items-center gap-3 px-4 sm:px-6 lg:px-8"><button class="icon-btn md:hidden" @click="sidebarOpen = true"><Menu :size="18" /></button><div class="relative max-w-xl flex-1"><Search :size="16" class="absolute left-3 top-1/2 -translate-y-1/2 text-[#609184]"/><input v-model="query" class="field h-10 pl-9 pr-16 text-sm" placeholder="Search your home…" @input="runSearch"/><span class="absolute right-3 top-1/2 hidden -translate-y-1/2 rounded-md border border-emerald-100/10 px-1.5 py-0.5 text-[10px] text-[#5c887d] sm:block">⌘ K</span><div v-if="searchResults.length" class="glass absolute left-0 right-0 top-12 z-50 overflow-hidden rounded-xl p-1.5 shadow-2xl"><button v-for="item in searchResults" :key="`${item.module}-${item.id}`" class="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left hover:bg-emerald-200/10" @click="goSearch(item)"><span class="rounded-md bg-emerald-200/10 px-1.5 py-1 text-[9px] uppercase text-emerald-200">{{ item.module }}</span><span class="min-w-0 flex-1 truncate text-xs text-white">{{ item.title }}<span class="block truncate text-[10px] text-[#6e9b8e]">{{ item.subtitle || item.group }}</span></span></button></div></div><div class="ml-auto flex items-center gap-2"><button class="icon-btn relative" title="Notifications" @click="router.push('/notifications')"><Bell :size="17" /><span v-if="notifications" class="absolute -right-1 -top-1 flex h-4 min-w-4 items-center justify-center rounded-full bg-rose-400 px-1 text-[9px] font-bold text-[#3c0d17]">{{ notifications > 9 ? '9+' : notifications }}</span></button><div class="hidden h-7 w-px bg-emerald-100/10 sm:block"></div><RouterLink to="/profile" class="flex items-center gap-2 rounded-xl p-1.5 pr-2 transition hover:bg-emerald-200/10"><span class="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-emerald-200 to-cyan-300 text-xs font-bold text-[#062421]">{{ initials }}</span><span class="hidden text-left sm:block"><span class="block max-w-[110px] truncate text-xs font-semibold text-white">{{ auth.user?.name }}</span><span class="block text-[10px] capitalize text-emerald-200/55">{{ auth.user?.roles?.[0]?.replace('-', ' ') || 'Household member' }}</span></span></RouterLink><button class="icon-btn hidden sm:inline-flex" title="Sign out" @click="logout"><LogOut :size="16" /></button></div></div></header><main class="min-h-[calc(100vh-72px)] px-4 py-5 sm:px-6 sm:py-7 lg:px-8"><RouterView /></main></div>
        <AiMascot :open="aiOpen" :listening="aiListening" :processing="aiProcessing" @toggle="aiOpen = !aiOpen" /><AiChat v-if="aiOpen" :open="aiOpen" @close="aiOpen = false" @listening="aiListening = $event" @processing="aiProcessing = $event" />
    </div>
</template>
